<?php
/**
 * Language labels for database tables/fields belonging to extension "jk_poll"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"tx_jkpoll_poll" => "Poll",	
		"tx_jkpoll_poll.title" => "Title",	
		"tx_jkpoll_poll.image" => "Image",
		"tx_jkpoll_poll.question" => "Question",	
		"tx_jkpoll_poll.votes" => "Votes",	
		"tx_jkpoll_poll.answers" => "Answers",
		"tx_jkpoll_poll.colors" => "Colors",
		"tt_content.list_type_pi1" => "Poll",
		'tt_content.pi_flexform.sheet_settings' => 'General Settings',
		'tt_content.pi_flexform.what_to_display' => 'What to display:',
		'tt_content.pi_flexform.amount' => 'Amount of polls (LIST):',
		'tt_content.pi_flexform.sheet_template' => 'Template',
		'tt_content.pi_flexform.type' => 'Type',
		'tt_content.pi_flexform.templatefile' => 'Template',
		'tt_content.pi_flexform.type_horizontal' => 'horizontal',
		'tt_content.pi_flexform.type_vertical' => 'vertical',
		'tt_content.pi_flexform.color' => 'Color:',
		'tt_content.pi_flexform.height_width' => 'Height/Width',
		'tt_content.pi_flexform.factor' => 'Factor',
		'tt_content.pi_flexform.PIDitemDisplay' => 'Page for Single-view (POLL)',
		'tt_content.pi_flexform.show_first' => 'Show first poll in LIST:',
		'tt_content.pi_flexform.fe_user' => 'Allow only fe_users to vote:',
		'tt_content.pi_flexform.check_ip' => 'Check IP before vote is possible:',
		'tt_content.pi_flexform.time' => 'Allow another vote after x hours (if IP check is enabled):',
		'tt_content.pi_flexform.vote_old' => 'Allow votes for old polls in LIST:',
		'tt_content.pi_flexform.cookie' => 'Set cookie for x days (value "off" for non-persistent cookie):',
		'tt_content.pi_flexform.captcha' => 'Use captcha (Extension Captcha is required):',
		'tt_content.pi_flexform.list' => 'Include link to list of old polls:',
		'tt_content.pi_flexform.PIDforward' => 'Page to forward to after vote:',
		'tx_jkpoll_poll.valid_till' => "valid till",
		'tx_jkpoll_poll.title_tag' => "Title Text",
        'tx_jkpoll_poll.alternative_tag' => "Alternative Text",
        'tx_jkpoll_poll.width' => "Width (pixels)",
        'tx_jkpoll_poll.height' => "Height (pixels)",
        'tx_jkpoll_poll.link' => "Link",
        'tx_jkpoll_poll.clickenlarge' => "Click-enlarge",
        'tt_content.pi_flexform.sheet_language' => 'Multilanguage',
        'tx_jkpoll_poll.vote_language_specific' => "Count votes for every language:",
        'tx_jkpoll_poll.check_language_specific' => "Check if user can vote for every language:",
        'tx_jkpoll_poll.first_answer_selected' => "First answer is checked by default:",
	),
	"dk" => Array (
		"tx_jkpoll_poll" => "Afstemning",	
		"tx_jkpoll_poll.title" => "Titel",	
		"tx_jkpoll_poll.question" => "Spørgsmål",	
		"tx_jkpoll_poll.answers" => "Svarmuligheder",	
		"tt_content.list_type_pi1" => "Poll",	
	),
	"de" => Array (
		"tx_jkpoll_poll" => "Umfrage",
		"tx_jkpoll_poll.title" => "Titel",	
		"tx_jkpoll_poll.image" => "Bild",
		"tx_jkpoll_poll.question" => "Frage",
		"tx_jkpoll_poll.votes" => "Stimmen",	
		"tx_jkpoll_poll.answers" => "Antworten",
		"tx_jkpoll_poll.colors" => "Farben",	
		"tt_content.list_type_pi1" => "Umfrage",
		'tt_content.pi_flexform.sheet_settings' => 'Allgemeine Einstellungen',
		'tt_content.pi_flexform.what_to_display' => 'Ansicht:',
		'tt_content.pi_flexform.amount' => 'Anzahl der Umfragen (LIST):',
		'tt_content.pi_flexform.sheet_template' => 'Template',
		'tt_content.pi_flexform.type' => 'Typ',
		'tt_content.pi_flexform.templatefile' => 'Template',
		'tt_content.pi_flexform.type_horizontal' => 'horizontal',
		'tt_content.pi_flexform.type_vertical' => 'vertikal',
		'tt_content.pi_flexform.color' => 'Farbe:',
		'tt_content.pi_flexform.height_width' => 'Höhe/Breite',
		'tt_content.pi_flexform.factor' => 'Faktor',
		'tt_content.pi_flexform.PIDitemDisplay' => 'Seite für die Single-Anzeige (POLL)',
		'tt_content.pi_flexform.show_first' => 'Zeige erste Umfrage in LIST:',
		'tt_content.pi_flexform.check_ip' => 'IP vor Stimmenabgabe prüfen:',
		'tt_content.pi_flexform.fe_user' => 'Stimmenabgabe nur für FE User:',
		'tt_content.pi_flexform.time' => 'Nächste Stimmenabgabe nach x Stunden erlauben (wenn IP-Überprüfung aktiviert):',
		'tt_content.pi_flexform.vote_old' => 'Stimmenabgabe für alte Umfragen in LIST erlauben:',
		'tt_content.pi_flexform.cookie' => 'Cookie gültig für x Tage (Wert "off" für non-persistent Cookie):',
		'tt_content.pi_flexform.captcha' => 'Verwende captcha (Extension Captcha wird benötigt):',
		'tt_content.pi_flexform.list' => 'Link zu alten Umfragen hinzufügen:',
		'tt_content.pi_flexform.PIDforward' => 'Weiterleiten zu Seite nach Abstimmung:',
		'tx_jkpoll_poll.valid_till' => "gültig bis",
		'tx_jkpoll_poll.title_tag' => "Titel Text",
        'tx_jkpoll_poll.alternative_tag' => "Alternativer Text",
        'tx_jkpoll_poll.width' => "Breite (Pixel)",
        'tx_jkpoll_poll.height' => "Höhe (Pixel)",
        'tx_jkpoll_poll.link' => "Verweis",
        'tx_jkpoll_poll.clickenlarge' => "Klick-vergrössern",
        'tt_content.pi_flexform.sheet_language' => 'Mehrsprachigkeit',
        'tx_jkpoll_poll.vote_language_specific' => "Stimmen pro Sprache zählen:",
        'tx_jkpoll_poll.check_language_specific' => "Stimmenabgabe pro Sprache prüfen:",
        'tx_jkpoll_poll.first_answer_selected' => "Erste Antwort vorselektiert:",
	),
	"fi" => Array (
		"tx_jkpoll_poll" => "Kysely",	
		"tx_jkpoll_poll.title" => "Otsikko",	
		"tx_jkpoll_poll.image" => "Kuva",
		"tx_jkpoll_poll.question" => "Kysymys",	
		"tx_jkpoll_poll.answers" => "Vastaukset",	
		"tt_content.list_type_pi1" => "Kysely",
		'tt_content.pi_flexform.sheet_settings' => 'Yleiset asetukset',
		'tt_content.pi_flexform.what_to_display' => 'Mitä näytetään:',
		'tt_content.pi_flexform.amount' => 'Kyselyjen määrä (LIST):',
		'tt_content.pi_flexform.sheet_template' => 'Template',
		'tt_content.pi_flexform.type' => 'Tyyppi',
		'tt_content.pi_flexform.templatefile' => 'Template',
		'tt_content.pi_flexform.type_horizontal' => 'horisontaalinen',
		'tt_content.pi_flexform.type_vertical' => 'vertikaalinen',
		'tt_content.pi_flexform.height_width' => 'Korkeus/Leveys',
		'tt_content.pi_flexform.factor' => 'Faktori',
		'tt_content.pi_flexform.PIDitemDisplay' => 'Single-view (POLL) sivu',
		'tt_content.pi_flexform.show_first' => 'Näytä ensimmäinen kysely:',
		'tt_content.pi_flexform.fe_user' => 'Anna äänestysoikeus vain käyttäjille fe_users:',
		'tt_content.pi_flexform.check_ip' => 'Tarkista IP ennen kuin äänestäminen on mahdollista:',
		'tt_content.pi_flexform.time' => 'Salli uusi äänestys x tunnin päästä (jos IP-tarkistus on päällä):',
		'tt_content.pi_flexform.vote_old' => 'Salli vanhojen kyselyjen äänestäminen:',
		'tt_content.pi_flexform.cookie' => 'Aseta eväste x päiväksi (arvo "off" väliaikaiselle evästeelle):',
		'tt_content.pi_flexform.captcha' => 'Käytä captcha (Ext Captcha on pakollinen):',
		'tt_content.pi_flexform.list' => 'Sisällytä linkki vanhoihin kyselyihin:',
		'tx_jkpoll_poll.valid_till' => "voimassa",
	),
);
?>